/**
{
    companyNum: String,
	quarterCode: String,
	assignNum: String,
    labelExpand: String,
	device: String,
	area: String,
	equipment: String,
	label: String,
	expand: String,
	detectTime: String,
	detectStartDate: Date,
	detectEndDate: Date,
	detectPeople: String,
	instrument: String,
	detectBackgroundValue: Number,
	detectValue: Number,
	threshold: Number,
	isLeak: String,
	repairPeople: String,
    repairCount: String,
    repairEndDate: Date,
    repairUseTime: String,
	repairMeasure: String,
    retestStartDate: Date,
    retestEndDate: Date,
    retestInstrument: String,
	afterLeakRate: String,
    retestPeople: String,
    retestValue: Number,
    retestBackgroundValue: Number,
    isDelayRepair: String,
    delayRepairReason: String,
    planRepairDate: Date,
}
 */
const detectLedgerCollection = mongoDb.collection('detectLedger')
module.exports = detectLedgerCollection
